#spring.application.name=gateway
server:
  port: 8000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://auth-and-security
              predicates:
                - Path=/api/v1/user-service/**
              filters:
                - RewritePath=/api/v1/user-service/(?<segment>.*), /$\{segment}
            - id: approval-system
              uri: lb://approval-system
              predicates:
                - Path=/api/v1/approval-system/**
              filters:
                - RewritePath=/api/v1/approval-system/(?<segment>.*), /$\{segment}
            - id: attendance-tracking
              uri: lb://attendance-tracking
              predicates:
                - Path=/api/v1/attendance-tracking/**
              filters:
                - RewritePath=/api/v1/attendance-tracking/(?<segment>.*), /$\{segment}
            - id: communication-and-alarm
              uri: lb://communication-and-alarm
              predicates:
                - Path=/api/v1/communication-and-alarm/**
              filters:
                - RewritePath=/api/v1/communication-and-alarm/(?<segment>.*), /$\{segment}
            - id: resource-reservation
              uri: lb://resource-reservation
              predicates:
                - Path=/api/v1/resource-reservation/**
              filters:
                - RewritePath=/api/v1/resource-reservation/(?<segment>.*), /$\{segment}


eureka:

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: +i12AQFwws/Del1pGAOB0imXQLGaCNd7dyMF41Mxe6k=